steps:
    # Build the container image
    - name: 'gcr.io/cloud-builders/docker'
      id: 'Build'
      args:
          [
              'build',
              '-t',
              '${_REGION}-docker.pkg.dev/homespace-digital/containers/${_WEB_SERVICE_NAME}:$COMMIT_SHA',
              '.'
          ]

    # # Push the container image to Container Registry
    - name: 'gcr.io/cloud-builders/docker'
      id: 'Push'
      args: ['push', '${_REGION}-docker.pkg.dev/homespace-digital/containers/${_WEB_SERVICE_NAME}:$COMMIT_SHA']

    # # Deploy container image to Cloud Run
    - name: 'gcr.io/cloud-builders/gcloud'
      id: 'Deploy'
      entrypoint: gcloud
      args:
          - 'run'
          - 'deploy'
          - '${_WEB_SERVICE_NAME}'
          - '--image'
          - '${_REGION}-docker.pkg.dev/homespace-digital/containers/${_WEB_SERVICE_NAME}:$COMMIT_SHA'
          - '--region'
          - '${_REGION}'
          - '--service-account'
          - '${_SERVICE_ACCOUNT}'
          - '--allow-unauthenticated'
